# Generated by Django 5.0.3 on 2024-03-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Colaborator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("EDV", models.IntegerField(unique=True)),
                ("full_name", models.CharField(max_length=100)),
                ("responsibillity", models.CharField(max_length=100)),
                ("sector", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("schedule_work", models.TimeField()),
                ("date_start", models.DateField()),
                ("date_end", models.DateField()),
                ("perfil_image", models.CharField(max_length=100)),
            ],
        ),
    ]
