# Generated by Django 5.0.3 on 2024-03-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("amount", models.IntegerField()),
                ("weight", models.DecimalField(decimal_places=2, max_digits=5)),
                ("volts", models.IntegerField(choices=[(110, "110V"), (220, "220V")])),
                (
                    "voltage",
                    models.CharField(
                        choices=[
                            ("Microsoft", "Microsoft"),
                            ("Apple", "Apple"),
                            ("Bosch", "Bosch"),
                            ("Samsumg", "Samsumg"),
                            ("Xiaomi", "Xiaomi"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("Portable", "Portable"), ("Static", "Static")],
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
